database:
  host: order-form-mongo.local

site title: Operation WinterGreen
products:
  - id: burro-tail
    name: Burro's Tail (Sedum morganianum)
    description: "This is a cutting from an extremely overgrown plant. It has blunt, talon-shaped leaves that come off the purplish-brown main central stem easily, so handle with care. 2-20 inches depending on package limits, leaves may detach from the stem in travel. This succulent can grow wildly long if forgotten, as it stores water for long periods in the leaves. underwatering is less lethal to this plant than overwatering. the white-silver bloom on the outside of the leaf is natural and not a symptom of powdery mildew; the xeric preferences of this plant generally prevent mold from growing on it in the first place. Won't poison mammal pets."
    soil type: cactus mix or 1:2:3 perlite-potting mix-large sand
  - name: Willow (salix discolor, pussywillow)
    id: willow
    description: This is a cutting from an outdoor willow tree. It should have green buds and long white or red roots; stems 6-18 inches depending on package limits. They grow quickly and love water. Don't plant it outside, as it can be invasive. You could technically get salicylic acid from this plant, but please don't eat anything i send to you. Pet safe.
    soil type: any, prefers that which holds water longer
  - id: swedish-ivy
    name: Swedish Ivy (plectranthus certicillatus, creeping charlie)
    description: This is a cutting from an overgrown creeping charlie that has been rooting in water for several weeks. 5-16 inches depending on package limits, and may be mildly bent in travel. If the stem kinks, you can cut it into two plants; the rootless one will make roots if you set the bare stem in soil. It WILL overgrow itself without semi-regular pruning once it's established. It's pretty reactive to changes in environment, changing color quickly when watered. You can water from the top, as the leaves seem to soak up moisture quickly. This plant requires good drainage, loves to climb, anmd makes tiny white flowers when it's happy. The abundant sap is orange-red, don't be alarmed when you trim it and get some on your skin, it's not harmful and comes off with soap. pet safe.
    soil type: fluffed potting mix with perlite or similar-texture soil
  - name: Pothos (Epipremnum aureum, devil's ivy)
    id: pothos
    description: This is a cutting from an overgrown pothos with 2-4 leaves that has been rooting in water for several weeks. I don't have many of these. 4 inches or so. It has a vining habit with heart-shaped leaves. Water it less often, it tolerates drought. Leaves are vareigated with white and yellow. NOT PET FRIENDLY!
    soil type: 1-1 ratio fluffed potting mix and cactus mix, or just the former
    max: 1
client: /web-services/order-form/client
